from typing import TypedDict, List

class AgentState(TypedDict):
    """
    State dictionary for the LangGraph workflow.
    """
    customer_name: str         # Name of the customer
    session_id: str            # Unique ID for the current session
    user_query: str            # The raw query submitted by the customer
    intent: str                # Classified intent: Sales, Technical, Billing, Account, Memory, or Unknown
    department: str            # Department the query was routed to
    retrieved_context: str     # Top-k document chunks retrieved by RAG
    memory_context: str        # Previous conversation history loaded from SQLite
    approval_required: bool    # Whether this request requires human approval
    approval_status: str       # One of: "pending", "approved", "rejected", "N/A"
    response: str              # The current draft response generated by the agent
    final_response: str        # The polished response after Supervisor review
    conversation_history: list # Full list of turns in the current session
    retrieved_chunks: list     # List of individual retrieved chunk strings for display
